"""Render docs/COVERAGE_SF_ISSUES.md from seohead.sf.core.sf_issue_map.

Kept beside the data so the committed document and the drift test read the same code path,
exactly as CHECKS.md and TOOL_REFERENCE.md already do.
"""

from __future__ import annotations

from seohead.sf.core.sf_issue_map import CATEGORIES, coverage_counts

__all__ = ["render"]

_STATUS_LABEL = {
    "check": "check",
    "tool": "tool",
    "partial": "partial",
    "gap": "gap",
    "out_of_scope": "out of scope",
}

_BULK_CATEGORIES = ("Accessibility", "AMP")


def _refs(refs: tuple[str, ...]) -> str:
    return " ".join(f"`{r}`" for r in refs) if refs else "—"


def _header() -> list[str]:
    counts = coverage_counts()
    total = sum(counts.values())
    bulk = sum(len(CATEGORIES[name]) for name in _BULK_CATEGORIES)
    in_scope = total - bulk
    covered = counts["check"] + counts["tool"]
    return [
        "# Coverage against the published issue catalogue",
        "",
        "*Generated by `scripts/generate_sf_coverage.py` from `seohead/sf/core/sf_issue_map.py`.",
        "Do not edit by hand.*",
        "",
        "Screaming Frog publishes a list of the issues its crawler reports — the closest thing",
        "technical SEO has to a shared checklist. This measures us against it, because a count",
        "of our own checks is a number with nothing to compare to.",
        "",
        "**Only the issue names are used.** They are the field's shared vocabulary for these",
        "problems, and naming a problem is not copying a description of it. Every explanation",
        "here is written about *our own* behaviour.",
        "",
        "## Where we stand",
        "",
        "| Status | Count | Meaning |",
        "|---|---:|---|",
        f"| check | {counts['check']} | a registry check finds it |",
        f"| tool | {counts['tool']} | a command outside the crawl registry finds it |",
        f"| partial | {counts['partial']} | we find part of it; the missing part is stated |",
        f"| gap | {counts['gap']} | we should find it and do not |",
        f"| out of scope | {counts['out_of_scope']} | a decision, with its reason |",
        f"| **total** | **{total}** | |",
        "",
        f"{bulk} of the out-of-scope entries are two whole categories declined as single",
        "decisions — accessibility and AMP, each explained in its own section below. Of the",
        f"remaining {in_scope} issues, **{covered} are found today**, {counts['partial']} are",
        f"found in part, {counts['gap']} are gaps worth closing, and",
        f"{counts['out_of_scope'] - bulk} need something we have decided not to build.",
        "",
        "A gap is not a defect. It is a named, deliberate absence — which is the only kind worth",
        "having, because the alternative is an absence nobody has noticed.",
        "",
    ]


def render() -> str:
    lines = _header()
    for category, items in CATEGORIES.items():
        if category in _BULK_CATEGORIES:
            continue
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Issue | Status | Found by | Note |")
        lines.append("|---|---|---|---|")
        for entry in items:
            note = entry.note.replace("|", "\\|")
            lines.append(
                f"| {entry.name} | {_STATUS_LABEL[entry.status]} | {_refs(entry.refs)} | {note} |"
            )
        lines.append("")

    for category in _BULK_CATEGORIES:
        items = CATEGORIES[category]
        lines.append(f"## {category}")
        lines.append("")
        lines.append(f"**{len(items)} issues, declined as one decision.** {items[0].note}")
        lines.append("")
        lines.append("<details><summary>The full list, so the decision is auditable</summary>")
        lines.append("")
        for entry in items:
            lines.append(f"- {entry.name}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
